### ISSUE TITLE
Could not install/compile in windows

### ISSUE THREAD

**Issue by dy** [jussi-kalliokoski/node-dsp#5]
Hi!
Tried to [benchmark](https://github.com/dfcreative/fourier-transform) this lib:

`npm install dsp`

``` sh
...
  c:\users\dmitry\.node-gyp\6.0.0\include\node\v8.h(888): note: see declaration of 'v8::HandleScope'
..\src\float32array.cpp(26): error C2039: 'GetCurrent': is not a member of 'v8::Context' [C:\Users\dmitry\Dropbox\Proje
cts\fourier-transform\node_modules\dsp\build\node-dsp.vcxproj]
  c:\users\dmitry\.node-gyp\6.0.0\include\node\v8.h(6754): note: see declaration of 'v8::Context'
..\src\float32array.cpp(26): error C3861: 'GetCurrent': identifier not found [C:\Users\dmitry\Dropbox\Projects\fourier-
transform\node_modules\dsp\build\node-dsp.vcxproj]
..\src\float32array.cpp(26): error C2227: left of '->Global' must point to class/struct/union/generic type [C:\Users\dm
itry\Dropbox\Projects\fourier-transform\node_modules\dsp\build\node-dsp.vcxproj]
  ..\src\float32array.cpp(26): note: type is 'unknown-type'
..\src\float32array.cpp(27): error C2039: 'New': is not a member of 'v8::String' [C:\Users\dmitry\Dropbox\Projects\four
ier-transform\node_modules\dsp\build\node-dsp.vcxproj]
  c:\users\dmitry\.node-gyp\6.0.0\include\node\v8.h(2099): note: see declaration of 'v8::String'
..\src\float32array.cpp(27): error C2664: 'v8::Local<v8::Object> Float32Array::New(int)': cannot convert argument 1 fro
m 'const char [13]' to 'int' [C:\Users\dmitry\Dropbox\Projects\fourier-transform\node_modules\dsp\build\node-dsp.vcxpro
j]
  ..\src\float32array.cpp(27): note: There is no context in which this conversion is possible
..\src\float32array.cpp(30): error C2661: 'v8::Local<v8::Function>::New': no overloaded function takes 1 arguments [C:\
Users\dmitry\Dropbox\Projects\fourier-transform\node_modules\dsp\build\node-dsp.vcxproj]
..\src\float32array.cpp(32): error C2660: 'v8::Integer::NewFromUnsigned': function does not take 1 arguments [C:\Users\
dmitry\Dropbox\Projects\fourier-transform\node_modules\dsp\build\node-dsp.vcxproj]
..\src\float32array.cpp(38): error C2872: 'Float32Array': ambiguous symbol [C:\Users\dmitry\Dropbox\Projects\fourier-tr
ansform\node_modules\dsp\build\node-dsp.vcxproj]
  c:\users\dmitry\dropbox\projects\fourier-transform\node_modules\dsp\src\float32array.h(6): note: could be 'Float32Arr
  ay' (compiling source file ..\src\float32array.cpp)
  c:\users\dmitry\.node-gyp\6.0.0\include\node\v8.h(3768): note: or       'v8::Float32Array' (compiling source file ..\
  src\float32array.cpp)
..\src\float32array.cpp(40): error C2039: 'GetIndexedPropertiesExternalArrayDataType': is not a member of 'v8::Object'
[C:\Users\dmitry\Dropbox\Projects\fourier-transform\node_modules\dsp\build\node-dsp.vcxproj]
  c:\users\dmitry\.node-gyp\6.0.0\include\node\v8.h(2635): note: see declaration of 'v8::Object'
..\src\float32array.cpp(41): error C2065: 'kExternalFloatArray': undeclared identifier [C:\Users\dmitry\Dropbox\Project
...and alike
```

node6, win7, node-gyp is setup properly.

**Comment by Pecacheu** [comment]
I can't install the library either. I'm on Linux. I think the project is dead and no longer working with current Node.js versions.

**Comment by j-funk** [comment]
I'm on osx and can't install either:

```
> dsp@0.0.3 install /Users/jaboing/Documents/git/local_dev/voice_online/node_modules/dsp
> node-gyp rebuild

  CXX(target) Release/obj.target/node-dsp/src/module.o
In file included from ../src/module.cpp:3:
../src/dsp.h:6:30: error: expected class name
class NodeDSP : public node::ObjectWrap {
                             ^
../src/dsp.h:10:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Abs (const v8::Arguments &args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:11:46: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> AbsCplx (const v8::Arguments &args);
                                                    ^~~~~~~~~~~~~
                                                    v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:12:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Acos (const v8::Arguments &args);
                                                 ^~~~~~~~~~~~~
                                                 v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:13:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Add (const v8::Arguments &args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:14:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Asin (const v8::Arguments &args);
                                                 ^~~~~~~~~~~~~
                                                 v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:15:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Atan (const v8::Arguments &args);
                                                 ^~~~~~~~~~~~~
                                                 v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:16:44: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Atan2 (const v8::Arguments &args);
                                                  ^~~~~~~~~~~~~
                                                  v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:17:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Ceil (const v8::Arguments &args);
                                                 ^~~~~~~~~~~~~
                                                 v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:18:44: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Clamp (const v8::Arguments &args);
                                                  ^~~~~~~~~~~~~
                                                  v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:19:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Cos (const v8::Arguments &args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:20:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Div (const v8::Arguments &args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:21:46: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> DivCplx (const v8::Arguments &args);
                                                    ^~~~~~~~~~~~~
                                                    v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:22:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Exp (const v8::Arguments &args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:23:44: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Floor (const v8::Arguments &args);
                                                  ^~~~~~~~~~~~~
                                                  v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:24:44: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Fract (const v8::Arguments &args);
                                                  ^~~~~~~~~~~~~
                                                  v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:25:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Log (const v8::Arguments &args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:26:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Madd (const v8::Arguments &args);
                                                 ^~~~~~~~~~~~~
                                                 v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cpp:3:
../src/dsp.h:27:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Max (const v8::Arguments &args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/jaboing/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/node-dsp/src/module.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jaboing/Documents/git/local_dev/voice_online/node_modules/dsp
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN install:dsp@0.0.3 dsp@0.0.3 install: `node-gyp rebuild`
npm WARN install:dsp@0.0.3 Exit status 1
```

**Comment by jussi-kalliokoski** [comment]
The project is not dead, strictly speaking, but it isn't very alive either. I'd be happy to give maintainership to someone willing and with more time on their hands than me. :)
